/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ServerMainFrame.java
 *
 * Created on Feb 25, 2012, 11:44:17 AM
 */
package server;

import java.awt.HeadlessException;
import java.awt.MenuItem;
import java.awt.PopupMenu;
import java.awt.Toolkit;
import java.awt.TrayIcon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.SwingUtilities;

/**
 *
 * @author Administrator
 */
public class ServerMainFrame extends javax.swing.JFrame {

    private Server server = new Server(this);
    

    /** Creates new form ServerMainFrame */
    public ServerMainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.changeStatusTS(DISCONNECTED);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bamboo Caro Server");
        setIconImage(Toolkit.getDefaultToolkit().getImage("src/images/icon.png"));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(500, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        jPanel1.add(btnStart);

        btnStop.setText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });
        jPanel1.add(btnStop);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        txtText.setBackground(new java.awt.Color(0, 0, 0));
        txtText.setColumns(20);
        txtText.setEditable(false);
        txtText.setFont(new java.awt.Font("Tahoma", 0, 14));
        txtText.setForeground(new java.awt.Color(255, 255, 255));
        txtText.setRows(5);
        txtText.setText("\n");
        jScrollPane1.setViewportView(txtText);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
    this.changeStatusTS(BEGIN_CONNECT);
    server.startServer();
    server.waitForConnections();
    this.changeStatusTS(CONNECTED);
}//GEN-LAST:event_btnStartActionPerformed

private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
    this.changeStatusTS(DISCONNECTING);
    server.shutdown();
    this.changeStatusTS(DISCONNECTED);
}//GEN-LAST:event_btnStopActionPerformed

private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    this.changeStatusTS(DISCONNECTING);
    server.shutdown();
    this.changeStatusTS(DISCONNECTED);
}//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ServerMainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtText;
    // End of variables declaration//GEN-END:variables

    public void printMsb(final String msg) {
        SwingUtilities.invokeLater(new Runnable() {

            @Override
            public void run() {
                txtText.append(msg);
            }
        });
    }


    public void changeStatusTS(final int status) {
        SwingUtilities.invokeLater(new Runnable() {

            @Override
            public void run() {
                switch (status) {
                    case BEGIN_CONNECT:
                        btnStart.setEnabled(false);
                        btnStop.setEnabled(false);
                        break;

                    case CONNECTED:
                        btnStart.setEnabled(false);
                        btnStop.setEnabled(true);
                        break;

                    case DISCONNECTING:
                        btnStart.setEnabled(false);
                        btnStop.setEnabled(false);
                        break;
                    case DISCONNECTED:
                        btnStart.setEnabled(true);
                        btnStop.setEnabled(false);
                        break;

                    default:
                        break; // do nothing
                }

                repaint();
            }
        });

    }
    public final static int DISCONNECTED = 1;
    public final static int DISCONNECTING = 2;
    public final static int BEGIN_CONNECT = 3;
    public final static int CONNECTED = 4;

    
}
