/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EmoticonPane.java
 *
 * Created on Feb 28, 2012, 8:21:01 PM
 */
package client;

import java.awt.Point;
import java.awt.Shape;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.geom.RoundRectangle2D;
import java.io.File;
import java.net.MalformedURLException;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Administrator
 */
public class EmoticonPane extends javax.swing.JDialog implements MouseListener {

    private Shape shape;
    private DashBoardPanel dashBoardPanel;

    /** Creates new form EmoticonPane */
    public EmoticonPane(java.awt.Frame parent, boolean modal, DashBoardPanel dashBoardPanel) {
        super(parent, modal);
        this.dashBoardPanel = dashBoardPanel;
        initShape();
        initComponents();
        setActionListenerToButtons();
    }

    public void popup(int x, int y) {        
        this.setLocation(x, y);
        this.setVisible(!this.isVisible());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn10 = new javax.swing.JButton();
        btn105 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn113 = new javax.swing.JButton();
        btn117 = new javax.swing.JButton();
        btn120 = new javax.swing.JButton();
        btn28 = new javax.swing.JButton();
        btn124 = new javax.swing.JButton();
        btn127 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn130 = new javax.swing.JButton();
        btn131 = new javax.swing.JButton();
        btn26 = new javax.swing.JButton();
        btn99 = new javax.swing.JButton();
        btn53 = new javax.swing.JButton();
        btn74 = new javax.swing.JButton();
        btn54 = new javax.swing.JButton();
        btn72 = new javax.swing.JButton();
        btn67 = new javax.swing.JButton();
        btn77 = new javax.swing.JButton();
        btn81 = new javax.swing.JButton();
        btn70 = new javax.swing.JButton();
        btn83 = new javax.swing.JButton();
        btn97 = new javax.swing.JButton();
        btn96 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusCycleRoot(false);
        setIconImage(null);
        setResizable(false);
        setShape(getShape());
        setUndecorated(true);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel1.setLayout(new java.awt.GridLayout(5, 5, 2, 2));

        btn10.setForeground(new java.awt.Color(231, 0, 0));
        btn10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emoticons/10.gif"))); // NOI18N
        btn10.setContentAreaFilled(false);
        btn10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn10.setFocusable(false);
        btn10.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btn10.setName("10"); // NOI18N
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        jPanel1.add(btn10);

        btn105.setForeground(new java.awt.Color(231, 0, 0));
        btn105.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emoticons/105.gif"))); // NOI18N
        btn105.setContentAreaFilled(false);
        btn105.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn105.setFocusable(false);
        btn105.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btn105.setName("105"); // NOI18N
        btn105.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn105ActionPerformed(evt);
            }
        });
        jPanel1.add(btn105);

        btn11.setForeground(new java.awt.Color(231, 0, 0));
        btn11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emoticons/11.gif"))); // NOI18N
        btn11.setContentAreaFilled(false);
        btn11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn11.setFocusable(false);
        btn11.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btn11.setName("11"); // NOI18N
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });
        jPanel1.add(btn11);

        btn113.setForeground(new java.awt.Color(231, 0, 0));
        btn113.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emoticons/113.gif"))); // NOI18N
        btn113.setContentAreaFilled(false);
        btn113.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn113.setFocusable(false);
        btn113.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btn113.setName("113"); // NOI18N
        btn113.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn113ActionPerformed(evt);
            }
        });
        jPanel1.add(btn113);

        btn117.setForeground(new java.awt.Color(231, 0, 0));
        btn117.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emoticons/117.gif"))); // NOI18N
        btn117.setContentAreaFilled(false);
        btn117.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn117.setFocusable(false);
        btn117.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btn117.setName("117"); // NOI18N
        btn117.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn117ActionPerformed(evt);
            }
        });
        jPanel1.add(btn117);

        btn120.setForeground(new java.awt.Color(231, 0, 0));
        btn120.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emoticons/120.gif"))); // NOI18N
        btn120.setContentAreaFilled(false);
        btn120.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn120.setFocusable(false);
        btn120.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btn120.setName("120"); // NOI18N
        btn120.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn120ActionPerformed(evt);
            }
        });
        jPanel1.add(btn120);

        btn28.setForeground(new java.awt.Color(231, 0, 0));
        btn28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emoticons/28.gif"))); // NOI18N
        btn28.setContentAreaFilled(false);
        btn28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn28.setFocusable(false);
        btn28.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btn28.setName("28"); // NOI18N
        btn28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn28ActionPerformed(evt);
            }
        });
        jPanel1.add(btn28);

        btn124.setForeground(new java.awt.Color(231, 0, 0));
        btn124.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emoticons/124.gif"))); // NOI18N
        btn124.setContentAreaFilled(false);
        btn124.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn124.setFocusable(false);
        btn124.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btn124.setName("124"); // NOI18N
        btn124.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn124ActionPerformed(evt);
            }
        });
        jPanel1.add(btn124);

        btn127.setForeground(new java.awt.Color(231, 0, 0));
        btn127.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emoticons/127.gif"))); // NOI18N
        btn127.setContentAreaFilled(false);
        btn127.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn127.setFocusable(false);
        btn127.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btn127.setName("127"); // NOI18N
        btn127.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn127ActionPerformed(evt);
            }
        });
        jPanel1.add(btn127);

        btn13.setForeground(new java.awt.Color(231, 0, 0));
        btn13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emoticons/13.gif"))); // NOI18N
        btn13.setContentAreaFilled(false);
        btn13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn13.setFocusable(false);
        btn13.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btn13.setName("13"); // NOI18N
        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });
        jPanel1.add(btn13);

        btn130.setForeground(new java.awt.Color(231, 0, 0));
        btn130.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emoticons/130.gif"))); // NOI18N
        btn130.setContentAreaFilled(false);
        btn130.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn130.setFocusable(false);
        btn130.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btn130.setName("130"); // NOI18N
        btn130.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn130ActionPerformed(evt);
            }
        });
        jPanel1.add(btn130);

        btn131.setForeground(new java.awt.Color(231, 0, 0));
        btn131.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emoticons/131.gif"))); // NOI18N
        btn131.setContentAreaFilled(false);
        btn131.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn131.setFocusable(false);
        btn131.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btn131.setName("131"); // NOI18N
        btn131.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn131ActionPerformed(evt);
            }
        });
        jPanel1.add(btn131);

        btn26.setForeground(new java.awt.Color(231, 0, 0));
        btn26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emoticons/26.gif"))); // NOI18N
        btn26.setContentAreaFilled(false);
        btn26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn26.setFocusable(false);
        btn26.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btn26.setName("26"); // NOI18N
        btn26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn26ActionPerformed(evt);
            }
        });
        jPanel1.add(btn26);

        btn99.setForeground(new java.awt.Color(231, 0, 0));
        btn99.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emoticons/99.gif"))); // NOI18N
        btn99.setContentAreaFilled(false);
        btn99.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn99.setFocusable(false);
        btn99.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btn99.setName("99"); // NOI18N
        btn99.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn99ActionPerformed(evt);
            }
        });
        jPanel1.add(btn99);

        btn53.setForeground(new java.awt.Color(231, 0, 0));
        btn53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emoticons/53.gif"))); // NOI18N
        btn53.setContentAreaFilled(false);
        btn53.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn53.setFocusable(false);
        btn53.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btn53.setName("53"); // NOI18N
        btn53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn53ActionPerformed(evt);
            }
        });
        jPanel1.add(btn53);

        btn74.setForeground(new java.awt.Color(231, 0, 0));
        btn74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emoticons/74.gif"))); // NOI18N
        btn74.setContentAreaFilled(false);
        btn74.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn74.setFocusable(false);
        btn74.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btn74.setName("74"); // NOI18N
        btn74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn74ActionPerformed(evt);
            }
        });
        jPanel1.add(btn74);

        btn54.setForeground(new java.awt.Color(231, 0, 0));
        btn54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emoticons/54.gif"))); // NOI18N
        btn54.setContentAreaFilled(false);
        btn54.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn54.setFocusable(false);
        btn54.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btn54.setName("54"); // NOI18N
        btn54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn54ActionPerformed(evt);
            }
        });
        jPanel1.add(btn54);

        btn72.setForeground(new java.awt.Color(231, 0, 0));
        btn72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emoticons/72.gif"))); // NOI18N
        btn72.setContentAreaFilled(false);
        btn72.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn72.setFocusable(false);
        btn72.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btn72.setName("72"); // NOI18N
        btn72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn72ActionPerformed(evt);
            }
        });
        jPanel1.add(btn72);

        btn67.setForeground(new java.awt.Color(231, 0, 0));
        btn67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emoticons/67.gif"))); // NOI18N
        btn67.setContentAreaFilled(false);
        btn67.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn67.setFocusable(false);
        btn67.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btn67.setName("67"); // NOI18N
        btn67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn67ActionPerformed(evt);
            }
        });
        jPanel1.add(btn67);

        btn77.setForeground(new java.awt.Color(231, 0, 0));
        btn77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emoticons/77.gif"))); // NOI18N
        btn77.setContentAreaFilled(false);
        btn77.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn77.setFocusable(false);
        btn77.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btn77.setName("77"); // NOI18N
        btn77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn77ActionPerformed(evt);
            }
        });
        jPanel1.add(btn77);

        btn81.setForeground(new java.awt.Color(231, 0, 0));
        btn81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emoticons/81.gif"))); // NOI18N
        btn81.setContentAreaFilled(false);
        btn81.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn81.setFocusable(false);
        btn81.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btn81.setName("81"); // NOI18N
        btn81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn81ActionPerformed(evt);
            }
        });
        jPanel1.add(btn81);

        btn70.setForeground(new java.awt.Color(231, 0, 0));
        btn70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emoticons/70.gif"))); // NOI18N
        btn70.setContentAreaFilled(false);
        btn70.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn70.setFocusable(false);
        btn70.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btn70.setName("70"); // NOI18N
        btn70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn70ActionPerformed(evt);
            }
        });
        jPanel1.add(btn70);

        btn83.setForeground(new java.awt.Color(231, 0, 0));
        btn83.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emoticons/83.gif"))); // NOI18N
        btn83.setContentAreaFilled(false);
        btn83.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn83.setFocusable(false);
        btn83.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btn83.setName("83"); // NOI18N
        btn83.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn83ActionPerformed(evt);
            }
        });
        jPanel1.add(btn83);

        btn97.setForeground(new java.awt.Color(231, 0, 0));
        btn97.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emoticons/97.gif"))); // NOI18N
        btn97.setContentAreaFilled(false);
        btn97.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn97.setFocusable(false);
        btn97.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btn97.setName("97"); // NOI18N
        btn97.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn97ActionPerformed(evt);
            }
        });
        jPanel1.add(btn97);

        btn96.setForeground(new java.awt.Color(231, 0, 0));
        btn96.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emoticons/96.gif"))); // NOI18N
        btn96.setContentAreaFilled(false);
        btn96.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn96.setFocusable(false);
        btn96.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btn96.setName("96"); // NOI18N
        btn96.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn96ActionPerformed(evt);
            }
        });
        jPanel1.add(btn96);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
}//GEN-LAST:event_btn10ActionPerformed

private void btn105ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn105ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btn105ActionPerformed

private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btn11ActionPerformed

private void btn113ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn113ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btn113ActionPerformed

private void btn117ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn117ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btn117ActionPerformed

private void btn120ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn120ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btn120ActionPerformed

private void btn28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn28ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btn28ActionPerformed

private void btn124ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn124ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btn124ActionPerformed

private void btn127ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn127ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btn127ActionPerformed

private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btn13ActionPerformed

private void btn130ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn130ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btn130ActionPerformed

private void btn131ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn131ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btn131ActionPerformed

private void btn26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn26ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btn26ActionPerformed

private void btn99ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn99ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btn99ActionPerformed

private void btn53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn53ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btn53ActionPerformed

private void btn74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn74ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btn74ActionPerformed

private void btn54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn54ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btn54ActionPerformed

private void btn72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn72ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btn72ActionPerformed

private void btn67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn67ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btn67ActionPerformed

private void btn77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn77ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btn77ActionPerformed

private void btn81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn81ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btn81ActionPerformed

private void btn70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn70ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btn70ActionPerformed

private void btn83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn83ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btn83ActionPerformed

private void btn97ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn97ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btn97ActionPerformed

private void btn96ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn96ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btn96ActionPerformed

private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
this.setVisible(false);
}//GEN-LAST:event_formFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn105;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn113;
    private javax.swing.JButton btn117;
    private javax.swing.JButton btn120;
    private javax.swing.JButton btn124;
    private javax.swing.JButton btn127;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn130;
    private javax.swing.JButton btn131;
    private javax.swing.JButton btn26;
    private javax.swing.JButton btn28;
    private javax.swing.JButton btn53;
    private javax.swing.JButton btn54;
    private javax.swing.JButton btn67;
    private javax.swing.JButton btn70;
    private javax.swing.JButton btn72;
    private javax.swing.JButton btn74;
    private javax.swing.JButton btn77;
    private javax.swing.JButton btn81;
    private javax.swing.JButton btn83;
    private javax.swing.JButton btn96;
    private javax.swing.JButton btn97;
    private javax.swing.JButton btn99;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void initShape() {
        shape = new RoundRectangle2D.Float(20, 20, 400, 400, 50, 50);
    }

    private void setActionListenerToButtons() {
        JButton[] buttons = {btn10, btn105, btn11, btn113, btn117, btn120, btn124, btn127, btn13, btn130, btn131, btn26, btn28, btn53, btn54, btn67, btn70, btn72, btn74, btn77, btn81, btn83, btn96, btn97, btn99};
        for (JButton button : buttons) {
            button.addMouseListener(this);
        }
    }

    @Override
    public void mouseClicked(MouseEvent e) {
        this.setVisible(false);

        String cmd = ((JButton) e.getSource()).getName();
        String imgName = cmd + ".gif";
        String imagePathAbs = "";
        try {
            imagePathAbs = new File("src/images/emoticons/" + imgName).toURL().toExternalForm();
        } catch (MalformedURLException ex) {            
        }
        String imagePath = "src/images/emoticons/" + imgName;
        
        this.dashBoardPanel.appendImgToChatInput(new ImageIcon("src/images/emoticons/"+imgName), "<img src='" + imagePathAbs + "'/>");
    }

    @Override
    public void mousePressed(MouseEvent e) {
    }

    @Override
    public void mouseReleased(MouseEvent e) {
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }
}
