/*
 * ShowMessageDialog.java
 *
 */

package client;

import models.Account;

/**
 *
 * @author Group I (Sunshine Group) C0810L
 */
public class UserInfoDialog extends javax.swing.JDialog {

        /** Creates new form ShowMessageDialog */
    public UserInfoDialog(java.awt.Frame parent, DashBoardPanel dashBoardPanel, boolean modal, Account account) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(dashBoardPanel);
        this.txtFullName.setText(account.getFullname());
        this.txtUserName.setText(account.getUsername());
        this.txtTaken.setText(String.valueOf(account.getMatchsTaken()));
        this.txtWon.setText(String.valueOf(account.getMatchsWin()));
        
    }
    
     
   // <editor-fold defaultstate="collapsed" desc="paint">
    /*
    private Image image = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/dialog.png"));;
    @Override
    public void paint(Graphics g){
            
            g.drawImage(image,0,20,this);            
            message.setText(mess);            
            add(btnOK);
            add(btnCancel);

        }
     * */
    // </editor-fold>

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        message = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTaken = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtWon = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFocusCycleRoot(true);
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        message.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        message.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        message.setForeground(new java.awt.Color(186, 25, 25));
        message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        message.setText("User Info");
        message.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        message.setName("message"); // NOI18N
        jPanel1.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 20));

        btnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ok.png"))); // NOI18N
        btnOK.setText("OK");
        btnOK.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOK.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btnOK.setName("btnOK"); // NOI18N
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        jPanel1.add(btnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 60, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dialog.png"))); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 202, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setName("jPanel2"); // NOI18N

        jLabel3.setText("Username:");
        jLabel3.setName("jLabel3"); // NOI18N

        txtUserName.setEditable(false);
        txtUserName.setForeground(new java.awt.Color(196, 0, 0));
        txtUserName.setText("username");
        txtUserName.setBorder(null);
        txtUserName.setName("txtUserName"); // NOI18N

        jLabel4.setText("Full Name:");
        jLabel4.setName("jLabel4"); // NOI18N

        txtFullName.setEditable(false);
        txtFullName.setForeground(new java.awt.Color(196, 0, 0));
        txtFullName.setText("fullname");
        txtFullName.setBorder(null);
        txtFullName.setName("txtFullName"); // NOI18N

        jLabel5.setText("Matches Taken:");
        jLabel5.setName("jLabel5"); // NOI18N

        txtTaken.setEditable(false);
        txtTaken.setForeground(new java.awt.Color(196, 0, 0));
        txtTaken.setText("taken");
        txtTaken.setBorder(null);
        txtTaken.setName("txtTaken"); // NOI18N

        jLabel6.setText("Matches Won:");
        jLabel6.setName("jLabel6"); // NOI18N

        txtWon.setEditable(false);
        txtWon.setForeground(new java.awt.Color(196, 0, 0));
        txtWon.setText("won");
        txtWon.setBorder(null);
        txtWon.setName("txtWon"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtUserName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtFullName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtTaken, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtWon, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(txtUserName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(txtFullName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(txtTaken, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(txtWon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 250, 110));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        dispose();
}//GEN-LAST:event_btnOKActionPerformed

    /**
    * @param args the command line arguments
    */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel message;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtTaken;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtWon;
    // End of variables declaration//GEN-END:variables

}
